name: apidiff

on: [ pull_request ]

jobs:
  apidiff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: go-apidiff
      uses: joelanford/go-apidiff@v0.1.0
